### PR TITLE
Moving checkCrashResources to a more appropriate place

### PR DESCRIPTION
**Pull request by william-ferguson-au**
Namely to ConfigurationBuilder#build()

### CODE REVIEW

**Comment by F43nd1r** [comment]
Maybe ACRAConfigurationException could be a Runtime exception? This maintains best backwards compatibility. This exception should never be seen in production anyway, requiring users to always handle it seems like the wrong thing to me.

**Comment by william-ferguson-au** [comment]
No, we can't make it a RuntimeException.
One thing that a crash handler can't do is to crash itself.

We have to make it so that ACRA logs loudly that it has been misconfigured and is not running, but lets the app proceed.

**Comment by F43nd1r** [comment]
> One thing that a crash handler can't do is to crash itself.

That sounds reasonable, but then why are there exceptions in getConfig and getSharedPreferences? 

Next idea: throw exception in build(). Pass ConfigurationBuilder to init instead of ACRAConfiguration. This way we can have just one try/catch block showing a reasonable warning.

**Comment by F43nd1r** [comment]
Something like this: https://github.com/F43nd1r/acra/commit/b15a2c956a70841b82faefa27f4da2e279c85800

**Comment by william-ferguson-au** [comment]
There are unchecked Exception in getACRASharedPreferences and getConfig because it was an attempt to provide clear info \on what would otherwise have been a possibly non-intuitive NullPointerException at some future point. And also part of the reason those 2 methods are deprecated.

**Pull request merged**
