### PR TITLE
Add ability to have custom CrashReportDialog v2

### PR DESCRIPTION
**Pull request by timrae**
Continuing on from #218, I've created a new base class for `CrashReportDialog` which implements the minimum functionality for sending a crash report, and allowed setting of an arbitrary Activity for the CrashReportActivity

### CODE REVIEW

**Comment by william-ferguson-au** [comment]
Thanks Tim. I'll check it out.

One thing I noticed is the naming for the classes appears to round the wrong way.
CrashReportDialog should be the super class and DefaultCrashReportDialog should be the sub class.

**Comment by timrae** [comment]
I don't think renaming CrashReportDialog is a good idea tbh, since it will
force developers to rename the class in the manifest of their apps. Failure
to do this will result in the app not sending any error reports, which
could lead to a lot of support requests. How about just renaming the parent
class? E.g. to BaseCrashReportDialog or something

**Comment by william-ferguson-au** [comment]
Yeah. Good point.
Just rename the parent to BaseCrashReportDialog then.
ᐧ

**Comment by timrae** [comment]
Done

**Comment by timrae** [comment]
Sorry to bother you William, but do you think you'll have time to release RC2 this week? We're basically only waiting on this change to be released now before we release AnkiDroid 2.4

**Comment by william-ferguson-au** [comment]
I hope to get to it tomorrow night.



ᐧ

**Comment by timrae** [comment]
FYI, it's [working great in AnkiDroid](https://gist.github.com/timrae/077da61e76c9a4346f89), looking forward to RC2.
untitled

**Comment by william-ferguson-au** [comment]
Tanks Tim.
Made a couple of changes.

The main one being that we also pass the Exception (EXTRA_REPORT_EXCEPTION intent arg) into BaseCrashReportDialog so that the Exception can be used to customise the dialog.

**Comment by william-ferguson-au** [comment]
I plan to cut 4.6.0RC2 tonight.
ᐧ

**Comment by timrae** [comment]
Thanks for the review, merge, and fine tuning! Great news about RC2

**Comment by jngr** [comment]
> Tanks Tim.
> Made a couple of changes.
> 
> The main one being that we also pass the Exception (EXTRA_REPORT_EXCEPTION intent arg) into BaseCrashReportDialog so that the Exception can be used to customise the dialog.

Humble question: why was it removed again in v. 5? Is there any way now to access the Exception from a custom dialog? This was rather useful.

Thanks,
-jngr

**Comment by F43nd1r** [comment]
@jngr this was removed because the dialog may be called at app startup, where the throwable obejct is not available. Currently the only thing you can do is load the report file, parse it and get the `STACKTRACE` field. 

#736 will introduce a new helper which does that for you (see `CrashReportDialogHelper#getReportData`)

**Comment by jngr** [comment]
> @jngr this was removed because the dialog may be called at app startup, where the throwable obejct is not available. Currently the only thing you can do is load the report file, parse it and get the `STACKTRACE` field.
> 
> #736 will introduce a new helper which does that for you (see `CrashReportDialogHelper#getReportData`)

Understand. I'll look forward to that. Thanks for the fantastic work you are doing! -jngr

**Pull request merged**
