### PR TITLE
Change LastModifiedComparator implementation to be identical with Long.compare()

### LINKED ISSUE #516: LastModifiedComparator file comparator is not transitive
Hello, we are receiving the following error:

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeLo(TimSort.java:743)
at java.util.TimSort.mergeAt(TimSort.java:479)
at java.util.TimSort.mergeCollapse(TimSort.java:406)
at java.util.TimSort.sort(TimSort.java:210)
at java.util.TimSort.sort(TimSort.java:169)
at java.util.Arrays.sort(Arrays.java:2010)
at org.acra.file.ReportLocator.getApprovedReports(ReportLocator.java:55)
at org.acra.util.ApplicationStartupProcessor.sendApprovedReports(ApplicationStartupProcessor.java:70)
at org.acra.ACRA.init(ACRA.java:272)
at org.acra.ACRA.init(ACRA.java:200)
```

It seems that LastModifiedComparator is not transitive:
```
final class LastModifiedComparator implements Comparator<File> {
    @Override
    public int compare(@NonNull File lhs, @NonNull File rhs) {
        return (int) (lhs.lastModified() - rhs.lastModified());
    }
}
```

It should be like this:

```
final class LastModifiedComparator implements Comparator<File> {
    @Override
    public int compare(@NonNull File lhs, @NonNull File rhs) {
        return Long.compare(lhs.lastModified(), rhs.lastModified());
    }
}
```

ACRA version: 4.9.0

### PR DESCRIPTION
**Pull request by kboyarshinov**
Resolve #516

### CODE REVIEW

**Comment by william-ferguson-au** [comment]
Thanks

**Comment by kboyarshinov** [comment]
Thank you. Btw when do you plan to publish next release?

**Comment by william-ferguson-au** [comment]
Good question.
Perhaps tonight.

**Comment by kboyarshinov** [comment]
Would be great!

**Pull request merged**
