### PR TITLE
FIX #327: SendWorker now works in the separate process service.

### LINKED ISSUE #327: Using separete process service for sending reports.
Related to #313.

Seems I found the solution for this problem. You should just put the `SendWorker` into separete process.

Here is example of my HockeyApp Sender: https://gist.github.com/romansl/5c5c8e756ad20001ba8f

What do you think?

### PR DESCRIPTION
**Pull request by romansl**
This is a basic implementation.

Possible improvements:
- Show notification while send task in progress (prevents from rare system-initiated process kill).
- Merge `SendService` and `SendWorker`.
- Self-stop `SendService` after delay.
- Subscribe to "Internet availabale" broadcast and start `SendService`.

### CODE REVIEW

**Comment by william-ferguson-au** [comment]
Will wait until 4.70 is released before merging this.

**Comment by xmenxwk** [comment]
Very good but showing notification is something I would avoid.

**Comment by andryr** [comment]
If a crash occurs on startup (eg in Application.onCreate()) it will enter in a infinite loop because of the Service.

**Comment by william-ferguson-au** [comment]
@andryr how does having the service cause an infinite loop?

**Comment by romansl** [comment]
Each process has its own Application instance.

**Comment by william-ferguson-au** [comment]
@romansl are you answering my question to @andryr ?

**Comment by romansl** [comment]
My solution for this problem:

```java
public class MyApplication extends Application {
	@Override
    public void onCreate() {
        super.onCreate();

        if (!getPackageName().equals(getAppNameByPID(android.os.Process.myPid()))) {
            return;
        }

        ACRA.init(this);
        ACRA.getErrorReporter().setReportSender(new HockeySender());

        // other initializations...
    }

    private String getAppNameByPID(int pid){
        ActivityManager manager = (ActivityManager) getSystemService(Context.ACTIVITY_SERVICE);

        for(ActivityManager.RunningAppProcessInfo processInfo : manager.getRunningAppProcesses()){
            if(processInfo.pid == pid){
                return processInfo.processName;
            }
        }

        return "";
    }
}
```

**Comment by romansl** [comment]
May be this check should be iside `ACRA.init()`.

**Comment by william-ferguson-au** [comment]
There are some problems with this implementation that need to be addressed.

Storing the ReportSender class instead of instance in ErrorReporter means that 
- ReportSender cannot be configured (there are definitely users who do this).
- ReportSender must have a no arg constructor

Options are 
- enforce a no-arg constructor for ReportSender and disallow config, breaking N installs.
- introduce ReportSenderFactory whose create method takes AppContext. Store the factory instead of ReportSender.
- ?

I'm leaning towards the Factory. It's a bigger change in API but that will make people better aware of the change in requirements for a bespoke ReportSender.

Thoughts?

**Comment by william-ferguson-au** [comment]
Closed in favour of #344

**Pull request closed without merging**
