### PR TITLE
Update HttpRequest.java

### PR DESCRIPTION
**Pull request by DenisZhadan**
Can use without net.iharder.Base64 ?

### CODE REVIEW

**Comment by william-ferguson-au** [comment]
We might be able to consider that now.
It means that we only support Android 8 (Froyo) and up.
Probably time to move.

Need to remove the dependency in the Maven POM and the (new) Gradle config.

**Comment by DenisZhadan** [comment]
At first, thanks for library ACRA.

I use Android Studio 1.4.1 with gradle (IntelliJ IDEA).
I like use source code - it is better solution for debug ;)
After adding your source (ACRA 4.7) to my project, I can't find "net.iharder.Base64".

But in file org.acra.collector.ConfigurationCollector.java 
You used library "android.util", from code:
import android.util.SparseArray;

P.S. Small optimization:  
my code before:
final String encoded = new String(Base64.encode(credentials.getBytes("UTF-8"), Base64.DEFAULT), "UTF-8");

my code after:
final String encoded = Base64.encodeToString(credentials.getBytes("UTF-8"), Base64.DEFAULT);

**Comment by william-ferguson-au** [comment]
"net.iharder.Base64" is a declared dependency. See the Maven POM or Gradle build config for ACRA.
Android Studio with Gradle doesn't seem to do a good job of automatically including declared dependencies. So you will currently need to include that manually into the build config of your app.

**Comment by william-ferguson-au** [comment]
Dropped in favour of #330 (which includes your commit)

**Pull request merged**
